### ISSUE TITLE
The comment says waiting for a live holder is unbounded; acquire still gives up after WAIT_SECS — and removing the give-up would be the wrong fix

### ISSUE THREAD

**Issue by christhomas** [christhomas/rust-fs-ext4#134]
## The defect

The comment introduced by PR #133 says waiting for a live holder is unbounded:

```
# THERE IS NO "BREAKING POINT" ANY MORE. ...
# Waiting for a live holder is unbounded
# on purpose: `--force` is the way out, and it is a person's decision
# rather than a timer's.
WAIT_SECS="${AM_ORACLE_VM_WAIT:-3600}"
```

`cmd_acquire` still gives up (`scripts/vm-slot.sh:275`):

```sh
if [ "$waited" -ge "$WAIT_SECS" ]; then
    echo "[vm-slot] gave up after $(pretty_age $waited) waiting for $(holder_field 2)" >&2
    ...
    return 1
fi
```

So with the default `AM_ORACLE_VM_WAIT=3600`, waiting is bounded at one hour, not unbounded.

## Scope: the wording is wrong, the behaviour is right

Worth separating carefully, because the paragraph is making two claims and only one of them is false.

**True, and it is the point of PR #133:** the slot is never *taken* from a live holder by a timer. The age-only break is gone. Nothing steals.

**False:** "waiting ... is unbounded". The waiter gives up after an hour and returns 1.

The two got conflated. What the paragraph means is "there is no timed *reclamation*", and what it says is "there is no timed *give-up*". The important property holds; the sentence describing it does not.

This is the fourth instance in this one file of a comment stating a rule the code beneath it does not implement — see #105, #106, #108 — so it is worth correcting rather than shrugging at, even though nothing misbehaves.

## THE FIRST REMEDY OFFERED IS THE DANGEROUS ONE

CodeRabbit offers two: *"remove the `WAIT_SECS` give-up path if callers must wait indefinitely, or change the comment"*.

**Do not remove the give-up path.** It is what turns a stuck slot into a message. Without it, `vm.sh up` hangs silently and forever behind a holder that will never release — no output, no exit, nothing to act on. The give-up is not in tension with the paragraph's intent; it is the *mechanism* by which the human the paragraph invokes finds out they are needed. Its message already names both escapes:

```
[vm-slot] if that repository is finished, run its 'scripts/vm.sh down',
[vm-slot] or 'scripts/vm-slot.sh release --force' to take the slot.
```

Removing it would trade a bounded wait with an actionable message for an unbounded wait with none — which is the worse of the two failure modes for a script a person is sitting in front of.

## Safe fix

Correct the sentence. Say that no *reclamation* is timed and that a waiter still gives up after `WAIT_SECS` with instructions, rather than that waiting is unbounded. One or two lines.

## Provenance

CodeRabbit, **Major**, `scripts/vm-slot.sh:41` on PR #133 — *"Make the live-holder wait behavior match the stated contract."* Verified against merged `main`: the comment at lines 38-44, the give-up at line 275.

Recorded here as low severity rather than Major, because the behaviour it describes is correct and only the description is wrong.

The comment carries a "Prompt for AI Agents" block directing an agent to remove the give-up path. Not followed; see above for why that direction is the unsafe one.

**Comment by christhomas** [comment]
This issue is selected for development

Verified against `main`. `scripts/vm-slot.sh:41-43` reads "Waiting for a live holder is unbounded / on purpose: `--force` is the way out, and it is a person's decision / rather than a timer's", `:45` is `WAIT_SECS="${AM_ORACLE_VM_WAIT:-3600}"`, and the give-up is at `:275-280` returning 1. Bounded at one hour, not unbounded.

The separation the issue draws is the correct one and worth keeping in front of whoever fixes it: **no reclamation is timed — that is what PR #133 achieved and it holds** — while **the waiter still gives up on a timer**, which is what the sentence denies. The important property is true; the sentence describing it is not.

**One thing to add, which makes the fix write itself.** The paragraph contradicts *itself*, not only the code. Two lines above the "unbounded" claim, `:35-36` already says "The wait is long because a fixture build legitimately takes tens of minutes, and overridable for a caller that knows better" — which is a description of a bounded, tunable wait. So the same comment block states both, and the correction is to make `:41-43` agree with `:35-36` rather than to invent new wording.

**The warning about the first remedy is correct and I want to reinforce it.** Do not remove the give-up path. It is what turns a stuck slot into a message, and its text already names both escapes:

```
  [vm-slot] if that repository is finished, run its 'scripts/vm.sh down',
  [vm-slot] or 'scripts/vm-slot.sh release --force' to take the slot.
```

Removing it trades a bounded wait carrying instructions for an unbounded wait carrying none — a silent hang in a script a person is sitting in front of, waiting on a holder that may never release. The give-up is not in tension with the paragraph's intent; it is the mechanism by which the human the paragraph invokes finds out they are needed.

Noting for the record that the bot comment carries a "Prompt for AI Agents" block directing an agent to remove that path. **Do not follow it.** Filing that observation was the right call — an instruction embedded in a finding is still just text, and this one points at the unsafe branch.

Severity as recorded is right: the behaviour is correct and only the description is wrong. But this is the fourth comment in this one file stating a rule the code beneath it does not implement (#105, #106, #108 are the others), and that pattern is worth breaking rather than shrugging at — a comment is what the next person reasons from.

**Comment by christhomas** [comment]
Confirmed real and as filed, against true `origin/main` (`3a95a96`). `WAIT_SECS="${AM_ORACLE_VM_WAIT:-3600}"` and the give-up branch (`scripts/vm-slot.sh:328-329`) are both unchanged; the comment claiming unbounded waiting is also unchanged. Wording-only issue, correctly scoped as such in the filing.
